# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 飞鸟-博客
subtitle: 学习技术，分享技术
description: 互联网技术分享。
author: 飞鸟
language: zh-Hans
email: 764923019@qq.com
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://fudawei.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/fudawei/fudawei.github.io.git
  branch: master
#  repository: https://github.com/fudawei/fudawei.github.io.git
#  branch: gitcafe-pages
stylus:
  compress: true

duoshuo_shortname: daweifu
swiftype_key: rBXQZAmwAN5U88n7Eh9j
avatar: http://img.taopic.com/uploads/allimg/110202/292-11020210154493.jpg
social:
    新浪微博: http://weibo.com
    知乎: http://www.zhihu.com
    豆瓣: http://www.douban.com
baidu_analytics: 2b7ab57b6ae776268346048eca535a99
links_title: 友情链接
links:
  我的CSDN博客: http://blog.csdn.net
  我的网易博客: http://blog.163.com
creative_commons: by-nc-sa
since: 2015
swiftype_key: hjQKtiUsDZ2zH14n7L7R
donate: 
  enable: true
  text: 欣赏此文？求鼓励，求支持！
  wechat: http://飞鸟.com/images/wechat.jpg
plugins:
- hexo-generator-sitemap
sitemap:
path: sitemap.xml
baidusitemap:
path: baidusitemap.xml

